### Criar um usuário
POST http://localhost:7070/users
Content-Type: text/plain

João Silva

### Listar usuários
GET http://localhost:7070/users

### Buscar usuário pelo ID
GET http://localhost:7070/users/122

### Deletar um usuário
DELETE http://localhost:7070/users/22

### Ver a hora do servidor
GET http://localhost:7070/time

### Teste websocket
GET ws://localhost:7070/chat